window.CARD_LEVELS = [
  { name: 'Percepción', eyebrow: 'Hay un universo en la forma en que te miro', cards: [
    '¿Qué impresión te di la primera vez que hablamos y qué detalle la provocó?',
    'Antes de conocerme bien, ¿qué imaginabas sobre mi vida?',
    '¿Qué creías que teníamos en común y después descubriste que era distinto?',
    '¿Qué característica mía tardaste más en notar?',
    'Si alguien nos viera juntos durante diez minutos, ¿cómo crees que describiría nuestra relación?',
    '¿Qué parte de mi personalidad crees que solo aparece cuando tengo confianza?',
    'Adivina qué plan elegiría yo hoy: salir a explorar, quedarnos en casa, ver gente o tener tiempo a solas. Explica tu elección.',
    '¿Qué cosa pequeña crees que puede mejorarme un mal día?',
    '¿Cómo notas que algo me entusiasma antes de que te lo diga?',
    '¿Qué hago cuando estoy incómodo que quizá pienso que nadie nota?',
    '¿En qué situaciones crees que siento más confianza en mí?',
    '¿Qué elogio crees que me cuesta aceptar?',
    'Completa sobre mí: «Parece que no te importa…, pero creo que sí».',
    '¿Qué crees que intento expresar cuando te cuento un problema: que me escuches, que me ayudes o algo diferente?',
    'Si tuvieras que reconocerme en una historia sin nombres, ¿qué detalle me delataría?',
    '¿Qué actividad crees que podría hacer durante horas sin aburrirme?',
    '¿Qué lado mío crees que la gente suele interpretar mal?',
    'Describe mi día de descanso ideal. Después te digo qué acertaste.',
    '¿Qué crees que me hace sentir querido sin necesidad de palabras?',
    '¿Qué situación cotidiana crees que me agota más de lo que aparento?',
    'Si yo fuera guía de un museo sobre un tema inesperado, ¿de qué sería?',
    '¿Qué papel crees que suelo tomar en un grupo: organizar, observar, animar, cuidar u otro?',
    '¿Qué crees que valoro más al elegir una amistad?',
    '¿En qué crees que nos parecemos más de lo que admitimos?',
    '¿Qué diferencia entre nosotras te llamó la atención desde el principio?',
    '¿Qué gesto mío interpretas como una invitación a acercarte?',
    '¿Cómo crees que prefiero celebrar una buena noticia?',
    '¿Qué objeto cotidiano me representaría y por qué?',
    '¿Qué crees que necesito más esta semana y qué te hace pensarlo?',
    '¿Qué habilidad mía crees que yo considero normal, aunque no lo sea?',
    'Inventa un premio que yo merecería por mi forma de ser. Justifica la nominación.',
    '¿Qué crees que me pone sentimental de manera inesperada?',
    '¿En qué situaciones crees que me cuesta pedir ayuda?',
    '¿Qué crees que yo contaría primero si alguien me preguntara cómo eres?',
    '¿Qué hábito mío te parecía extraño y ahora tiene sentido para ti?',
    'Describe con cariño cómo crees que intento impresionarte. Te diré si acertaste.',
    '¿Qué suposición sobre mí has tenido que corregir con el tiempo?',
    '¿Qué crees que me gustaría que reconocieras más?',
    'Completa: «Creo que te conozco bien cuando se trata de…, pero todavía me da curiosidad…».',
    'Cada quien diga una cosa que cree saber del otro, pero que nunca le ha preguntado. Compruébenla.'
  ]},
  { name: 'Conexión', eyebrow: 'Las historias que nos trajeron hasta aquí', cards: [
    '¿Qué detalle de tu vida actual te está dando una alegría que todavía no me has contado?',
    '¿Qué te emocionaba de pequeño y sigue despertando algo en ti?',
    '¿Cómo se demostraba el cariño en tu casa cuando crecías?',
    '¿Qué aprendiste sobre los desacuerdos al observar a las personas que te criaron?',
    'Cuenta un recuerdo de infancia que ayude a entender cómo eres.',
    '¿Qué costumbre de tu familia quieres conservar y cuál prefieres cambiar?',
    '¿Quién te hizo sentir comprendido en una etapa en la que lo necesitabas?',
    '¿Qué versión de ti extrañas un poco?',
    '¿Qué parte de crecer te resultó distinta de como la imaginabas?',
    'Completa: «Algo que antes me daba vergüenza y hoy acepto de mí es…».',
    '¿Qué decisión te cambió la vida sin que lo supieras en ese momento?',
    '¿Qué logro tuyo tiene una historia que poca gente conoce?',
    '¿Qué expectativa ajena estás intentando dejar atrás?',
    '¿Qué actividad te hace sentir tú mismo, sin tener que demostrar nada?',
    '¿Qué sueño has dejado en pausa, pero no has abandonado?',
    '¿Qué te cuesta disfrutar sin sentir culpa?',
    '¿Qué parte de tu vida parece sencilla desde fuera, pero te exige mucho?',
    'Cuando dudas de ti, ¿qué te ayuda de verdad?',
    '¿Qué te gustaría aprender aunque nunca llegaras a hacerlo especialmente bien?',
    'Cuéntame algo que todavía estés tratando de entender sobre ti.',
    '¿Qué momento hizo que quisieras seguir conociéndome?',
    'Cuenta una ocasión en la que intentaste impresionarme. ¿Me di cuenta?',
    '¿Qué recuerdo nuestro te hace reír cada vez que vuelve a tu cabeza?',
    '¿Qué momento cotidiano contigo y conmigo guardarías en una botella?',
    '¿Cuándo sentiste que podías bajar la guardia conmigo?',
    '¿Qué descubriste sobre ti al empezar esta relación?',
    '¿Qué costumbre nuestra apareció sin que la planeáramos?',
    '¿Qué aventura que salió mal terminó siendo una buena historia?',
    'Si nuestra relación fuera una comedia, ¿qué escena no podría faltar?',
    'Inventen el nombre de una etapa de su relación y cuenten por qué se llamaría así.',
    '¿Qué lugar se volvió especial para ti por algo que vivimos ahí?',
    '¿Qué te gustaría recuperar de cuando empezábamos?',
    '¿Qué disfrutas ahora de nosotros que al principio todavía no existía?',
    'Cuenta un recuerdo nuestro que sospeches que yo he olvidado.',
    '¿Qué experiencia nueva te gustaría compartir conmigo aunque se nos diera fatal?',
    '¿Qué hago que te ayuda a sentir que te tengo presente?',
    '¿Cómo se siente para ti que te escuchen de verdad?',
    'Completa: «Cuando tengo un día difícil, me ayuda que tú…».',
    '¿Qué tipo de ayuda agradeces y cuál puede hacerte sentir invadido?',
    '¿Qué te gustaría que celebráramos más, aunque parezca pequeño?',
    '¿Qué necesitas cuando estás en silencio y cómo puedo distinguirlo?',
    '¿Qué disfrutas hacer a solas y quieres seguir conservando?',
    '¿Cómo te gustaría que cuidáramos el tiempo con nuestras amistades?',
    '¿Qué responsabilidad cotidiana te pesa más de lo que parece?',
    'Diseñen una cita de muy bajo presupuesto que entusiasme a ambos.',
    '¿Qué significa para ti pasar tiempo de calidad juntos?',
    '¿Qué costumbre con el celular te gustaría que acordáramos?',
    '¿Qué gesto cariñoso prefieres en privado y cuál disfrutas en público?',
    '¿Cómo te gustaría que nos acompañáramos cuando uno esté enfermo o agotado?',
    'Inventen un ritual de cinco minutos para reconectarse en días ocupados.',
    '¿Qué tema te cuesta iniciar aunque sí quieras hablarlo conmigo?',
    '¿Cómo te das cuenta de qué te molesta: lo sabes enseguida o necesitas procesarlo?',
    'Completa: «Me resulta más fácil escuchar algo difícil cuando…».',
    '¿Qué frase nos serviría para pedir una pausa y dejar claro que retomaremos la conversación?',
    '¿Qué hace que una disculpa se sienta sincera para ti?',
    '¿Qué necesitas después de un desacuerdo para recuperar la cercanía?',
    '¿Qué diferencia hay para ti entre ceder por cariño y callarte para evitar un problema?',
    '¿Qué límite personal te gustaría expresar con más facilidad?',
    'Elijan un desacuerdo pequeño. Cada quien explique la postura del otro y pregunte si la entendió.',
    '¿Qué hemos aprendido a manejar mejor como equipo?',
    '¿Qué momento cotidiano te hace sentir atracción por mí?',
    '¿Qué forma de coqueteo te gustaría que mantuviéramos siempre?',
    '¿Qué diferencia hay para ti entre sentirte querido y sentirte deseado?',
    '¿Qué tipo de afecto disfrutas sin que tenga que conducir a nada más?',
    '¿Qué te ayuda a dejar atrás las preocupaciones y conectar con la intimidad?',
    '¿Cómo te gusta que te invite a tener un momento íntimo?',
    '¿Qué te ayuda a expresar lo que te gusta, lo que no y lo que todavía no sabes?',
    '¿Cómo te gustaría que manejáramos los momentos en que nuestras ganas no coinciden?',
    '¿Qué curiosidad romántica o íntima te gustaría conversar, sin compromiso de llevarla a la práctica?',
    'Cada quien describa un momento de cercanía que le gustaría compartir: puede ser tierno, juguetón o sensual.',
    '¿Cómo sería un día ordinario de la vida que te gustaría construir?',
    '¿Qué significa para ti tener suficiente dinero?',
    '¿Qué decisiones económicas consideras personales y cuáles conviene conversar en pareja?',
    '¿Qué sueño tuyo quisieras que apoyara sin intentar dirigirlo?',
    '¿Qué significa para ti formar una familia, tenga la forma que tenga?',
    '¿Qué lugar ocupan —o no— los hijos en el futuro que imaginas?',
    '¿Qué necesitarías conversar antes de mudarte por una oportunidad de uno de los dos?',
    '¿Qué tradición propia te gustaría que inventáramos?',
    'Imaginen una semana sin obligaciones. Armen un plan que incluya algo importante para cada quien.',
    '¿Qué te gustaría conservar de nosotros aunque cambien nuestras circunstancias?'
  ]},
  { name: 'Reflexión', eyebrow: 'En quiénes nos convertimos', cards: [
    '¿Qué partes de ti ves reflejadas en mí y qué te hace comprender eso sobre ti?',
    '¿Qué crees que me resulta fácil y que quizá no reconozco como una fortaleza?',
    '¿Qué has aprendido sobre ti al estar conmigo?',
    '¿Qué es lo que más admiras de mí? Cuéntame un momento en el que lo hayas visto.',
    'Completa: «Antes buscaba en una pareja…, y hoy valoro más…».',
    '¿Qué cualidad mía, que no sea física, te resulta más atractiva?',
    '¿Qué es lo que todavía intentas demostrarte a ti mismo?',
    '¿Qué crees que necesito escuchar ahora mismo? Después te diré si me hace sentido.',
    '¿Qué parte de ti has aprendido a tratar con más paciencia?',
    '¿Qué hacemos que nos permite mostrarnos vulnerables y qué nos ayudaría a cuidar esa confianza?',
    '¿Qué tenemos hoy que alguna vez deseaste encontrar en una relación?',
    '¿Cómo se complementan nuestras personalidades y en qué necesitamos hacer un esfuerzo consciente?',
    '¿Qué crees que veo en ti que a veces te cuesta ver por tu cuenta?',
    '¿Qué te gustaría dejar ir para vivir con más tranquilidad?',
    '¿Qué es lo que más te cuesta entender de mí y qué te gustaría preguntarme para acercarte a comprenderlo?',
    '¿Qué idea sobre el amor has cambiado con el tiempo?',
    '¿Qué hemos construido que no se ve en las fotos ni en los momentos especiales?',
    '¿Qué gesto mío te demuestra amor sin que tenga que decir una palabra?',
    '¿Qué cambió en tu vida porque nos conocimos?',
    '¿Qué costumbre nuestra quieres conservar y cuál merece que la reconsideremos?',
    'Si tuvieras que elegir una palabra para describir nuestra conexión, ¿cuál sería y por qué?',
    '¿Qué te haría sentir más cerca de mí en esta etapa de nuestra vida?',
    '¿Qué significa para ti comprometerte con alguien sin dejar de ser tú?',
    '¿Qué podríamos crear juntos que nos hiciera ilusión a ambos?',
    'Propongan una pequeña aventura para la próxima semana que los saque de la rutina. Elijan una que les entusiasme a los dos.',
    '¿Qué te gustaría que nuestro yo del futuro agradeciera que empezamos a cuidar hoy?',
    'Completa: «Quiero asumir más responsabilidad por…, y me ayudaría que tú…».',
    'Dime algo que valoras de nosotros y que no quisieras seguir dando por hecho.',
    '¿Qué respuesta mía de hoy te dio alegría, ternura o admiración?',
    '¿Qué te enseñó esta conversación sobre ti mismo?'
  ]}
];